# Generated by Django 2.1.5 on 2019-01-28 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('f_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_text', models.CharField(max_length=500)),
                ('post_title', models.CharField(max_length=60)),
                ('poster', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='forum.ForumUser')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
