# Generated by Django 2.1.5 on 2019-01-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumuser',
            name='user',
        ),
        migrations.AddField(
            model_name='forumuser',
            name='password',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='forumuser',
            name='username',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
