# Generated by Django 2.1.7 on 2019-02-14 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190128_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ForumUser',
        ),
    ]
