# Generated by Django 2.1.7 on 2019-02-14 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190214_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('f_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default=None, max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='forum.ForumUser'),
        ),
    ]
