# Generated by Django 2.1.7 on 2019-02-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190214_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuser',
            name='email',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
