# Generated by Django 2.1.7 on 2019-03-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forumuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumuser',
            name='email',
        ),
    ]
